import type { RichApiPollingMetadata, RichApiWebhookMetadata } from './types';

// Generated by scripts/generate-endpoints.ts. Do not edit by hand.
export interface RichApiAsyncEndpointMapEntry {
	polling: RichApiPollingMetadata | null;
	webhook: RichApiWebhookMetadata | null;
}

export const ASYNC_ENDPOINT_MAP: Record<string, RichApiAsyncEndpointMapEntry> = {
  "v2_company_enricher": {
    "polling": null,
    "webhook": null
  },
  "v2_email_finder": {
    "polling": null,
    "webhook": null
  },
  "v2_email_verifier": {
    "polling": null,
    "webhook": null
  },
  "v2_person_enricher": {
    "polling": null,
    "webhook": null
  },
  "v2_phone_finder": {
    "polling": null,
    "webhook": null
  },
  "email_finding": {
    "polling": null,
    "webhook": {
      "request_field": "webhook",
      "delivery_events": [
        "job.completed",
        "job.failed"
      ],
      "signature_header": "X-TexAu-Signature",
      "signature_algorithm": "hmac-sha256"
    }
  },
  "email_verification": {
    "polling": null,
    "webhook": {
      "request_field": "webhook",
      "delivery_events": [
        "job.completed",
        "job.failed"
      ],
      "signature_header": "X-TexAu-Signature",
      "signature_algorithm": "hmac-sha256"
    }
  }
}
;
